name = "Qiwi modpack (personal)"
author = "dozed-dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c508f032aafce6799b45e9984a91909fb68caf69202247cfd281ed4423cd219"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
