name = "Qiwi modpack (personal)"
author = "dozed-dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb9e5d4ef2e07c43461d51f3849b15afb9595b273183994a0039ab13e0f4eca7"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
