name = "Qiwi modpack (personal)"
author = "dozed-dev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6c613c115055b1c880a5b39e05b2b01fa7a3a56a6fc14eb6fafa6f03b7edd13"

[versions]
fabric = "0.16.5"
minecraft = "1.21"
